# Generated by Django 4.2.7 on 2025-11-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COMPANY_ADMIN', 'Company Admin'), ('CONTRACTOR', 'Contractor'), ('WORKER', 'Worker'), ('DOCUMENT_CONTROLLER', 'Document Controller'), ('CONSULTANT', 'Consultant')], max_length=20),
        ),
    ]
