# Generated by Django 4.2.7 on 2025-11-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='other_info',
            field=models.TextField(blank=True, help_text='Additional company information', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(blank=True, help_text='Company login password', max_length=128, null=True),
        ),
    ]
