# Generated by Django 4.2.7 on 2025-11-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_DELAYED', 'Task Delayed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_APPROVED', 'Document Approved'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('BLUEPRINT_UPLOADED', 'Blueprint Uploaded'), ('BLUEPRINT_APPROVED', 'Blueprint Approved'), ('BLUEPRINT_REJECTED', 'Blueprint Rejected'), ('BLUEPRINT_MODIFICATION_REQUESTED', 'Blueprint Modification Requested'), ('COMMENT_ADDED', 'Comment Added'), ('DEADLINE_APPROACHING', 'Deadline Approaching')], max_length=35),
        ),
    ]
