# Generated by Django 4.2.7 on 2025-11-14 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='review_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MODIFICATION_REQUESTED', 'Modification Requested'), ('EXPIRED', 'Review Expired')], default='PENDING', max_length=25),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_blueprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='consultant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CONSULTANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulted_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
