# Generated by Django 4.2.7 on 2025-11-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('max_projects', models.IntegerField(default=1, help_text='0 for unlimited')),
                ('max_tasks_per_project', models.IntegerField(default=50, help_text='0 for unlimited')),
                ('max_departments', models.IntegerField(default=3, help_text='0 for unlimited')),
                ('max_users', models.IntegerField(default=10, help_text='0 for unlimited')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('features', models.JSONField(default=list, help_text='List of feature names')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['price'],
            },
        ),
    ]
